
import React from 'react';

const General = () => {
  const terms = [
    "Shodan : 1st Dan black belt",
    "Nidan : 2nd Dan",
    "Sandan : 3rd Dan",
    "Yondan : 4th Dan",
    "Godan : 5th Dan",
    "Rokudan : 6th Dan",
    "Nanadan : 7th Dan",
    "Hachidan : 8th Dan",
    "Kyudan : 9th Dan",
    "Jyudan : 10th Dan",
    "Bushi: Great martial artist (Okinawan); Warlord (Japanese)",
    "Hanshi : Head person of an organization",
    "Karateka : A practitioner of Karate",
    "Kohai: A student junior to oneself",
    "Kyoshi: Master instructor",
    "Mudansha : Students without black belt rank",
    "Reigi renshi: Polished instructor",
    "Sensei: Instructor, Teacher",
    "Sempai: A senior student",
    "Shihan : Formal title, Master Instructor, or Teacher of Teachers",
    "Shushin : Referee in a bout",
    "Uchi Deshi: A live-in student",
    "Yudansha : Black belt holder (any rank)",
    "Ashi barai: Foot sweep",
    "Budo : Martial Way; Martial arts",
    "Busaganishi: Martial arts deity",
    "Bunkai: Study of kata applications and techniques",
    "Chiru no chan chan : Fast, springy action",
    "Chudan : Middle level",
    "Dan : Level",
    "Do : Way; Path",
    "Dojo : Training place",
    "Dojo kun : Dojo rules",
    "Gasshuku : Special karate training camp",
    "Gedan : Lower level",
    "Geri : Kick",
    "Gi: Jacket; training costume; tunic",
    "Go : Hard; unyielding",
    "Go kumite : Hard sparring",
    "Goju Ryu Karate Do : Hard / Soft style, empty handed Way",
    "Hai: Yes",
    "Hajime : Begin",
    "Hara : Stomach",
    "Heishugata : 'Closed Fist' kata (Sanchin and Tensho)",
    "Hidari : Left",
    "Hiji : Elbow",
    "Hiza : Knee",
    "Hojo undo : Supplementary exercises",
    "Honbu Dojo : Central dojo of an organization",
    "Ippon kumite : One point sparring",
    "Jodan : Upper level",
    "Ju : Soft; flexible",
    "Junbi Undo : Warm up exercises",
    "Kaishugata : 'Open fist' kata (Gekisai, Saifa, etc.)",
    "Kakie : Push hands",
    "Kamae : Combative posture",
    "Kamae te : Assume stance",
    "Kanji: Chinese characters",
    "Karate : Empty hand",
    "Karate-Do : The way of Karate",
    "Kata : Forms",
    "Keage : Snap action",
    "Kenkon : The symbol of the I.O.G.K.F. Literally 'Heaven and Earth'",
    "Ki o tsuke : Attention (phonetically 'kee-ut-ski')",
    "Kiai: Focusing shout",
    "Kihon : Basic techniques",
    "Kokomi: Thrust action",
    "Koshi: Ball of the foot",
    "Kumite : Sparring",
    "Kyu : White to brown belt rank",
    "Mae : Front",
    "Mawatte : Turn around",
    "Migi: Right",
    "Mokuso : Silent contemplation, meditation",
    "Muchimi: Heavy, sticky action",
    "Obi: Training uniform belt",
    "Oyo bunkai: Study of techiques in kata (similar to Bunkai but including follow-ups)",
    "Otagai: Training partner",
    "Randori: Free sparring, relaxed sparring (sometimes called 'Jiyu kumite')",
    "Rei: Bow",
    "Sandan gi: Three level sparring",
    "Seiken : Fore fist",
    "Seiza : Formal sitting position (kneeling on your haunches, feet crossed)",
    "Semete : Attacking partner",
    "Shime : Sanchin testing",
    "Shomen : The front",
    "Shugo : Line up",
    "Ski atte : Change hands",
    "Suri ashi : Sliding step",
    "Tai sabaki : Body evasion ability",
    "Tanden : Navel",
    "Te : Hand",
    "Ude : Forearm",
    "Ude tanren : Forearm conditioning",
    "Uke harai: Blocking exercises",
    "Ushiro : Back, rear",
    "Waza : Techniques",
    "Yobi undo : Warm up exercises",
    "Yakusoku kumite : Pre-arranged sparring",
    "Yame : Stop",
    "Yoi: Ready",
    "Yoko : Side",
    "Zanshin : Awareness",
    "Agura : Informal sitting (legs crossed)",
    "Asobidi: Playful martial arts",
    "Ayumi ashi : Natural stepping",
    "Chakuchki : Replacing",
    "Embusen : Pattern of a given kata",
    "Gai-wan : Outer arm",
    "Gohon kumite : Five step basic sparring",
    "Gyakute : Grappling, wrestling, joint locking (Literally 'hand reverses')",
    "Haishu : Back-hand; Closed hand",
    "Haisoku : Instep",
    "Happo sabaki: All types of footwork and evasion movements",
    "Hiku no chikara : The power of recoil",
    "Jiyu ippon : One step freestyle sparring",
    "Josokutei: Ball of the feet",
    "Judo : The Gentle Way",
    "Junan taiso : Stretching exercises",
    "Kaette : Return, or Go Back",
    "Kaikoken : Crab Fist",
    "Kaisho : Open hand",
    "Kakato : Heel",
    "Kakuto : Bent-wrist",
    "Keiko : Training (also means 'Joined fingertips')",
    "Keito : Chicken head wrist",
    "Kentsui: Fist hammer",
    "Ki: Mind, Spirit, Energy",
    "Kihon ippon : Basic one point sparring",
    "Kihon kumite : Basic sparring",
    "Kime : Focus of power",
    "Koken : Wrist Joint",
    "Koshin : Rearward",
    "Kyusho jutsu : The art of attacking the vital points of the body",
    "Ma : Distance between opponents",
    "Ma ai: Distancing",
    "Mae ukemi: Front fall / roll",
    "Maete : Jab (Literally 'Front Hand')",
    "Matte : Wait",
    "Morote no kamae : Augmented handed combative posture",
    "Nai-wan : Inner arm",
    "Nin : Perseverance; tolerance; endurance; patience.",
    "O swate : Sit down",
    "O tate : Stand up",
    "Reigi: Etiquette, manners (sometimes called 'Reishiki')",
    "Sandan kumite : Three step, three level sparring",
    "Sanbon kumite : Three step sparring",
    "Sanbon zuki: Three step sparring, one hand blocks three punch combination",
    "Seishin tanren : Forging oneself through karate training",
    "Shiho-wari: Breaking boards on four sides to test power, awareness and focus (sometimes called 'Tameshiwari')",
    "Shinzen : Shrine",
    "Shinzui: Truth",
    "Shizen tai: Natural position",
    "Tachi: Stances",
    "Tachi zen : Standing meditation",
    "Tameshiwari: Test of technique's power via breaking",
    "Tandoku Renshu : Preparatory exercise",
    "Tako ashi: Octopus foot",
    "Tenshin : Moving, shifting",
    "Tome : Return to original position",
    "Torite : Escape methods",
    "Tsugi ashi: Chassis step",
    "Ukete : Defending party",
    "Unsoku ho : Footwork",
    "Wan : Arm",
    "Yasume : At ease",
    "Zenshin : Forward",
    "Zuki or Tsuki: Punch or thrust (sometimes pronounced 'ski')"
  ];

  return (
    <ul className="space-y-2">
      {terms.map((term, index) => (
        <li key={index} className="text-gray-700">
          {term}
        </li>
      ))}
    </ul>
  );
};

export default General;
